vitrina/svh_service/api/urls.py
from django.urls import path
from . import views

app_name = 'svh_service'

urlpatterns = [
    path('get_app_alive/', views.get_app_alive, name='get_app_alive'),
    path('get_app_stat/', views.get_app_stat, name='get_app_stat'),
]

vitrina/svh_service/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views


app_name = 'svh_service'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('consignments', views.consignment_list, name='consignment_list'),
    path('consignments/<int:id>/', views.consignment_update, name='consignment_update'),
    path('consignments/<int:id>/update', views.consignment_update, name='consignment_update'),
    path('consignments/<int:id>/delete', views.consignment_delete, name='consignment_delete'),
    path('consignments/<int:id>/post', views.consignment_post, name='consignment_post'),
    path('consignments/<int:id>/rollback', views.consignment_rollback, name='consignment_rollback'),
    path('consignments/<int:id>/close', views.consignment_close, name='consignment_close'),

    path('<str:entity_type>/object_add', views.object_add, name='object_add'),   #########

    path('erase_filters/<str:entity>/', views.erase_filters, name='erase_filters'),

    path('carpass', views.carpass_list, name='carpass_list'),
    path('carpass/<int:id>/', views.carpass_update, name='carpass_update'),
    path('carpass/<int:id>/update', views.carpass_update, name='carpass_update'),
    path('carpass/<int:id>/delete', views.carpass_delete, name='carpass_delete'),
    path('carpass/<int:id>/post', views.carpass_post, name='carpass_post'),
    path('carpass/<int:id>/rollback', views.carpass_rollback, name='carpass_rollback'),
    path('carpass/<int:id>/close', views.carpass_close, name='carpass_close'),

    path('documents/<str:entity_type>/<int:entity_id>/add_document', views.document_add, name='document_add'),
    path('documents/<int:id>/update', views.document_update, name='document_update'),
    path('documents/<int:id>/delete', views.document_delete, name='document_delete'),
    path('documents/<int:id>/close', views.document_close, name='document_close'),
    path('documents/<int:id>/download', views.document_download, name='document_download'),

    path('contacts', views.contact_list, name='contact_list'),
    path('contacts/<int:id>/', views.contact_update, name='contact_update'),
    path('contacts/<int:id>/update', views.contact_update, name='contact_update'),
    path('contacts/<int:id>/delete', views.contact_delete, name='contact_delete'),
    path('contacts/<int:id>/post', views.contact_post, name='contact_post'),
    path('contacts/<int:id>/rollback', views.contact_rollback, name='contact_rollback'),
    path('contacts/<int:id>/close', views.contact_close, name='contact_close'),
]

vitrina/vitrina/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('svh_service/', include('svh_service.urls', namespace='svh_service')),
    path('api/', include('svh_service.api.urls', namespace='api')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vitrina/svh_service/models.py
import sys, os, configparser
from django.db import models
from django.conf import settings
from pathlib import Path
from django.core.validators import MaxValueValidator, MinValueValidator
from django.core.exceptions import ValidationError

config = configparser.ConfigParser()
config_file = os.path.join(Path(__file__).resolve().parent.parent, 'vitrina', 'config.ini')
if os.path.exists(config_file):
    config.read(config_file, encoding='utf-8')
else:
    print("error! config file doesn't exist"); sys.exit()

APP_TYPE = config['app']['app_type']

TYPE_CHOICES = ( 
        ("V", "участник ВЭД"), ("B", "таможенный представитель (брокер)"), ("O", "оператор СВХ"), ("H", "руководство СВХ"), )


class Profile(models.Model):
    """
    Данные об организации пользователя из auth_user (соответствуют сущности Contact)
    """
    user = models.OneToOneField(settings.AUTH_USER_MODEL,
                                on_delete=models.CASCADE)
    contact = models.IntegerField(unique=True) # Код клиента из программы Альта-СВХ
    type = models.CharField(max_length=1, blank=True, default='') # Тип пользователя
    name = models.CharField(max_length=150, blank=True, default='') # Наименование организации

    class Meta:
        ordering = ['-id']
        if APP_TYPE == 'client':
            managed = False
            db_table = 'svh_service_profile'
        
    
class Consignment(models.Model):
    """
    Партии товаров
    """
    guid = models.CharField(max_length=36, blank=True, default='') # Уникальный идентификатор записи (аналогичен Альта-СВХ)
    key_id = models.CharField(max_length=16, unique=True) # Ключ партии товара в Альта-СВХ. 
    contact = models.IntegerField(blank=True, null=True) # Код клиента 
    contact_name = models.CharField(max_length=150, blank=True, default='') # Наименование клиента
    contact_broker = models.IntegerField(blank=True, null=True) # Код брокера оформляющего товар
    broker_name = models.CharField(max_length=150, blank=True,  default='') # Наименование брокера
    nttn = models.CharField(max_length=100, blank=True, default='') # Номер транспортного документа
    nttn_date = models.DateField(blank=True, null=True) # Дата транспортного документа
    dkd = models.CharField(max_length=100, blank=True, default='') # Номер ДКД
    dkd_date = models.DateField(blank=True, null=True) # Дата ДКД
    goods = models.CharField(max_length=100, blank=True, default='') # Описание товаров
    weight = models.FloatField(default=0) # Вес партии товара
    dater = models.DateTimeField(blank=True, null=True) # Дата регистрации партии товара
    dateo = models.DateTimeField(blank=True, null=True) # Дата выдачи партии товара со склада
    id_enter = models.CharField(max_length=8, blank=True, default='') # Id пропуска въезда транпортного средства на терминал
    car =  models.CharField(max_length=30, blank=True, default='') # Номер транспортного средства 
    d_in = models.DateTimeField(blank=True, null=True) # Дата въезда транспортного средства на терминал
    d_out = models.DateTimeField(blank=True, null=True) # Дата выезда транспортного средства с терминала 
    guid_user = models.CharField(max_length=36, blank=True, default='') # GUID пользователя который создал эту запись

    datep = models.DateTimeField(blank=True, null=True) # дата последнего обновления записи в БД Альта-СВХ (при миграции записи)
    created = models.DateTimeField(auto_now_add=True, ) # Дата создания записи в БД Витрины
    updated = models.DateTimeField(auto_now=True, ) # Дата последнего обновления записи в БД Витрины
    posted = models.BooleanField(default=False) # флаг проводки
    post_date = models.DateTimeField(blank=True, null=True) # дата проводки
    post_user_id = models.CharField(max_length=36, blank=True, default='') # идентификатор пользователя  который провел запись
    was_posted = models.BooleanField(default=False) # флаг первичной проводки

    class Meta:
        ordering = ['-id']
        if APP_TYPE == 'client':
            managed = False
            db_table = 'svh_service_consignment'


class Carpass(models.Model):
    """
    Пропуска/транспортные средства
    """
    guid = models.CharField(max_length=36, blank=True, default='') # Уникальный идентификатор записи
    id_enter = models.CharField(max_length=8, unique=True) # Ключ пропуска на въезд  в Альта-СВХ
    ncar = models.CharField(max_length=255, blank=True, default='') # Номер машины
    dateen = models.DateField(blank=True, null=True) # Дата въезда
    timeen = models.TimeField(blank=True, null=True) # Время въезда
    ntir = models.CharField(max_length=50, blank=True, default='') # Номер документа доставки
    nkont = models.CharField(max_length=50, blank=True, default='') # Номер контейнера
    driver = models.CharField(max_length=150, blank=True, default='') # Наименование перевозчика
    drv_man = models.CharField(max_length=50, blank=True, default='') # ФИО водителя
    dev_phone = models.CharField(max_length=15, blank=True, default='') # Телефон водителя для связи
    contact = models.IntegerField(blank=True, null=True) # Код клиента 
    contact_name = models.CharField(max_length=150, blank=True, default='') # Наименование клиента
    contact_broker = models.IntegerField(blank=True, null=True) # Код брокера оформляющего товар
    broker_name = models.CharField(max_length=150, blank=True,  default='') # Наименование брокера
    place_n =  models.CharField(max_length=150, blank=True,  default='') # Номер стоянки – где находится машина
    dateex = models.DateField(blank=True, null=True) # дата выезда транспортного средства с терминала 
    timeex = models.TimeField(blank=True, null=True) # Время выезда
    
    datep = models.DateTimeField(auto_now_add=True) # Дата создания записи
    posted = models.BooleanField(default=False) # флаг проводки
    post_date = models.DateTimeField(blank=True, null=True) # дата проводки
    post_user_id = models.CharField(max_length=36, blank=True, default='') # идентификатор пользователя  который провел запись
    was_posted = models.BooleanField(default=False) # флаг первичной проводки

    class Meta:
        ordering = ['-id']
        if APP_TYPE == 'client':
            managed = False
            db_table = 'svh_service_carpass'



class Contact(models.Model):
    """
    Организации/Контакты (клиенты/брокеры/операторы свх/руководство свх)
    """
    contact = models.IntegerField(unique=True) # Код клиента из программы Альта-СВХ
    type = models.CharField(max_length=1, choices=TYPE_CHOICES, blank=False, default='') # Тип пользователя (литера)
    type_name = models.CharField(max_length=100, blank=True, default='')  # Тип пользователя (наименование)
    name = models.CharField(max_length=150, blank=True, default='') # Наименование организации  
    inn = models.CharField(max_length=12, blank=True, default='') # ИНН организации
    fio = models.CharField(max_length=100, blank=True, default='') # ФИО физлица организации. ФИО оператора СВХ
    email0 = models.EmailField(max_length=100, blank=True, default='')  # Почта для смены пароля и контактов по работе портала
    email1 = models.EmailField(max_length=100, blank=True, default='') # Почта отсылки сообщений
    email2 = models.EmailField(max_length=100, blank=True, default='') # Почта для передачи документов партии товара
    idtelegram = models.CharField(max_length=36, blank=True, default='') # Идентификатор ID messenger Telegram
    tags = models.CharField(max_length=100, blank=True, default='') # Список хэштегов
    # login = models.CharField(max_length=30, blank=True, default='') # Логин клиента (организации)
    # pwd = models.CharField(max_length=20, blank=True, default='') # Пароль входа в портал. Должен быть зашифрован

    f_stop = models.BooleanField(default=False) # Флаг приостановки пользования порталом
    guid_user = models.CharField(max_length=36, blank=True, default='') # GUID пользователя который создал эту запись
    datep = models.DateTimeField(auto_now_add=True) # Дата создания записи
    posted = models.BooleanField(default=False) # флаг проводки
    post_date = models.DateTimeField(blank=True, null=True) # дата проводки
    post_user_id = models.CharField(max_length=36, blank=True, default='') # идентификатор пользователя  который провел запись 


    class Meta:
        ordering = ['-id']
        if APP_TYPE == 'client':
            managed = False
            db_table = 'svh_service_contact'
        

class Document(models.Model):
    """
    Документы для партий товаров
    """
    docnum = models.CharField(max_length=36) # Номер документа
    docdate = models.DateTimeField(blank=True, null=True) # Дата документа
    docname = models.CharField(max_length=100, blank=True, default='') # Наименование документа
    file = models.FileField(upload_to='documents/', blank=True, null=True)

    docbody = models.BinaryField(blank=True, null=True) # Содержимое документа. Может быть zip
    f_zip = models.BooleanField(blank=True, default=False) # файл архивирован/неархивирован
    nfile = models.CharField(max_length=100, blank=True, default='') # Наименование файла

    guid_partia = models.CharField(max_length=100, blank=True, null=True) # Ссылка на партию товара (key_id)
    id_enter = models.CharField(max_length=8, blank=True, null=True) # Ссылка на пропуск

    guid_mail = models.CharField(max_length=36, blank=True, default='') # Uemail.guid. guid письма которое отослал этот документ 
    dates = models.DateTimeField(blank=True, null=True) # Дата отправки письма c документом

    guid_user = models.CharField(max_length=36, blank=True, default='') # GUID пользователя который создал эту запись
    datep = models.DateTimeField(auto_now_add=True) # Дата создания записи

    class Meta:
        ordering = ['-id']
        if APP_TYPE == 'client':
            managed = False
            db_table = 'svh_service_document'


class Message(models.Model):
    """
    Сообщения в сервисе Витрина между оператором свх и клиентом/брокером
    """

vitrina/svh_service/api/views.py
from datetime import datetime
from django.contrib.auth.models import User
from rest_framework import permissions, viewsets
from svh_service.models import Consignment, Carpass, Contact, Document, Uemail
from svh_service.api.serializers import StatSerializer, IsAliveSerializer
from django.http import JsonResponse
from rest_framework.authentication import BasicAuthentication
from rest_framework.permissions import IsAuthenticated


# class UserViewSet(viewsets.ModelViewSet):
#     queryset = User.objects.all().order_by('-date_joined')
#     serializer_class = UserSerializer
#     permission_classes = [permissions.IsAuthenticated]


def get_app_alive(request):
    # api endpoint to get app is_alive status
    current_datetime = datetime.now()
    app_name = 'svh_service'
    is_alive = True

    data = {'current_datetime': current_datetime,
            'app_name': app_name, 
            'is_alive': is_alive,
            }
    
    serializer = IsAliveSerializer(data)
    data_serialized = serializer.data
    
    return JsonResponse(data_serialized, safe=False)


def get_app_stat(request):
    # api endpoint to get app statistics
    current_datetime = datetime.now()
    consignments = Consignment.objects.all()
    carpass = Carpass.objects.all()
    contacts = Contact.objects.all()
    documents = Document.objects.all()
    uemails = Uemail.objects.all()

    data = {'current_datetime': current_datetime,
            'consignments': len(consignments),
            'carpass': len(carpass),
            'contacts': len(contacts),
            'documents': len(documents),
            'uemails': len(uemails),
            }
    
    serializer = StatSerializer(data)
    data_serialized = serializer.data
    
    return JsonResponse(data_serialized, safe=False)

vitrina/svh_service/templates/shv_service/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Альта-СВХ. Витрина</title>

  <link rel="stylesheet" href="{% static 'node_modules/bootstrap/dist/css/bootstrap.min.css' %}" >
  <link rel="stylesheet" href="{% static 'node_modules/bootstrap-icons/font/bootstrap-icons.css' %}">
  <link rel="stylesheet" href="{% static 'node_modules/bootstrap-table/dist/bootstrap-table.min.css' %}">
  <link rel="stylesheet" href="{% static 'node_modules/jquery-resizable-columns/dist/jquery.resizableColumns.css' %}">
  <link rel="stylesheet" href="{% static 'node_modules/dragtable/dragtable.css' %}">
  
  <link href="{% static 'css/news.css' %}" rel="stylesheet">
</head>

<body>

  <div class="sidebar" style="width: 15%; display: block" id="mySidebar">
      <div {% if request.user.profile.type == 'O' %} class="sidebar_button_close" 
           {% else %} class="sidebar_button_close_client" {% endif %}>
        <button {% if request.user.profile.type == 'O' %} class="button_show_sidebar" 
                {% else %} class="button_show_sidebar_client" {% endif %}
                onclick="w3_close()">&#9776;</button>
      </div>
      <a href="{% url 'svh_service:carpass_list' %}" class="a_button">ПРОПУСКА</a>
      <a href="{% url 'svh_service:consignment_list' %}" class="a_button">ПАРТИИ ТОВАРОВ</a>
      {% if request.user.profile.type == 'O' %} 
        <a href="{% url 'svh_service:contact_list' %}" class="a_button">ОРГАНИЗАЦИИ</a>
      {% endif %}


  </div>

  <div id="main" style="margin-left: 15%;">
    <div {% if request.user.profile.type == 'O' %} id="header" {% else %} id="header_client" {% endif %}>
      <button id="openNav" {% if request.user.profile.type == 'O' %} class="button_show_sidebar" 
                           {% else %} class="button_show_sidebar_client" {% endif %}
        style="display: none" onclick="w3_open()">&#9776;
      </button>
      <h3 id="header_title">
        Альта-СВХ. Витрина.
        {% if request.user.profile.type == 'O' %} Оператор СВХ. {% else %} Кабинет клиента. {% endif %}
      </h3>
      <span {% if request.user.profile.type == 'O' %} id="header_logout" {% else %} id="header_logout_client" {% endif %}>
        <span {% if request.user.profile.type == 'O' %} id="header_user" {% else %} id="header_user_client" {% endif %}>
          {{ request.user.profile.name|default:request.user.username }}
        </span>
        <a href="{% url 'svh_service:logout' %}"><img src="{% static 'icons/logout_white_24dp_1x.png' %}"></a>
      </span>
    </div>
    <div id="content">
      {% block content %}
      {% endblock %}
    </div>
  </div>



<script>
    if (sessionStorage.getItem('main_marginLeft')) {
      document.getElementById("main").style.marginLeft = sessionStorage.getItem('main_marginLeft');
      document.getElementById("mySidebar").style.width = sessionStorage.getItem('mySidebar_width');
      document.getElementById("mySidebar").style.display = sessionStorage.getItem('mySidebar_display');
      document.getElementById("openNav").style.display = sessionStorage.getItem('openNav_display');
    }

    function w3_open() {
      document.getElementById("main").style.marginLeft = "15%";
      document.getElementById("mySidebar").style.width = "15%";
      document.getElementById("mySidebar").style.display = "block";
      document.getElementById("openNav").style.display = 'none';
      sessionStorage.setItem('main_marginLeft', '15%')
      sessionStorage.setItem('mySidebar_width', '15%')
      sessionStorage.setItem('mySidebar_display', 'block')
      sessionStorage.setItem('openNav_display', 'none')
    }
    function w3_close() {
      document.getElementById("main").style.marginLeft = "0%";
      document.getElementById("mySidebar").style.display = "none";
      document.getElementById("openNav").style.display = "inline-block";
      sessionStorage.setItem('main_marginLeft', '0%')
      sessionStorage.setItem('mySidebar_display', 'none')
      sessionStorage.setItem('openNav_display', 'inline-block')
    }
</script>

<script src="{% static 'node_modules/jquery/dist/jquery.min.js' %}"></script>
<script src="{% static 'node_modules/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'node_modules/bootstrap-table/dist/bootstrap-table.min.js' %}"></script>
<script src="{% static 'node_modules/bootstrap-table/dist/extensions/resizable/bootstrap-table-resizable.js' %}"></script>
<script src="{% static 'node_modules/jquery-resizable-columns/dist/jquery.resizableColumns.js' %}"></script>
<script src="{% static 'node_modules/jquery-ui.js' %}"></script>
<script src="{% static 'node_modules/dragtable/jquery.dragtable.js' %}"></script>
<script src="{% static 'node_modules/bootstrap-table/dist/extensions/reorder-columns/bootstrap-table-reorder-columns.js' %}"></script>
<script src="{% static 'node_modules/tableExport.jquery.plugin/libs/FileSaver/FileSaver.min.js' %}"></script>
<script src="{% static 'node_modules/tableExport.jquery.plugin/tableExport.min.js' %}"></script>
<script src="{% static 'node_modules/tableExport.jquery.plugin/libs/jsPDF/jspdf.umd.min.js' %}"></script>
<script src="{% static 'node_modules/tableExport.jquery.plugin/libs/js-xlsx/xlsx.core.min.js' %}"></script>
<script src="{% static 'node_modules/bootstrap-table/dist/extensions/export/bootstrap-table-export.min.js' %}"></script>
<script src="{% static 'node_modules/bootstrap-table/dist/extensions/toolbar/bootstrap-table-toolbar.min.js' %}"></script>

</body>


</html>

vitrina/svh_service/templates/shv_service/update_universal.html
{% extends "shv_service/base.html" %}

{% block content %}

{% if entity.posted %}
<style>
  .form_fields_area { #id_contact_name, #id_broker_name {
    background-color: White;
    } }

.form_fields_area { #id_contact_name:hover, #id_broker_name:hover {
    box-shadow: None;
    cursor: auto;    } }
</style>
{% endif %}


<div id="modal_catalog_client" class="modal-1">
  <div class="modal-content-1">
    <div>
      <h5 class='block_name_detail_page'>Участники ВЭД</h5>
      <span class="close" onclick="close_modal_catalog('V')">&times;</span>
    </div>
    <table id="table" data-toggle="table" data-pagination="true" data-search="true" data-id-table="advancedTable"
    data-search-align="left" data-buttons-align="left">  
    <thead><tr>
      <th data-sortable="true" data-field="contact">Код клиента</th>
      <th data-sortable="true" data-field="name">Наименование организации</th>
      <th data-sortable="true" data-field="inn">ИНН</th>
      <th data-sortable="true" data-field="email1">E-mail</th>
      <th data-sortable="true" data-field="idtelegram">Telegram ID</th>
    </tr></thead>
    <tbody>
      {% for contact in contacts %}
      {% if contact.type == 'V' %}
      <tr>
        <td><div onclick="pick_contact('V', '{{contact.contact}}', '{{contact.name}}')">{{ contact.contact }}</div></td>
        <td><div onclick="pick_contact('V', '{{contact.contact}}', '{{contact.name}}')">{{ contact.name }}</div></td>
        <td><div onclick="pick_contact('V', '{{contact.contact}}', '{{contact.name}}')">{{ contact.inn }}</div></td>
        <td><div onclick="pick_contact('V', '{{contact.contact}}', '{{contact.name}}')">{{ contact.email1 }}</div></td>
        <td><div onclick="pick_contact('V', '{{contact.contact}}', '{{contact.name}}')">{{ contact.idtelegram }}</div></td>
      </tr>
      {% endif %}
      {% endfor %}
</tbody></table></div></div>

<div id="modal_catalog_broker" class="modal-1">
  <div class="modal-content-1">
    <div>
      <h5 class='block_name_detail_page'>Таможенные представители (брокеры)</h5>
      <span class="close" onclick="close_modal_catalog('B')">&times;</span>
    </div>
    <table id="table" data-toggle="table" data-pagination="true" data-search="true" data-id-table="advancedTable"
    data-search-align="left" data-buttons-align="left">  
    <thead><tr>
      <th data-sortable="true" data-field="contact">Код клиента</th>
      <th data-sortable="true" data-field="name">Наименование организации</th>
      <th data-sortable="true" data-field="inn">ИНН</th>
      <th data-sortable="true" data-field="email1">E-mail</th>
      <th data-sortable="true" data-field="idtelegram">Telegram ID</th>
    </tr></thead>
    <tbody>
      {% for contact in contacts %}
      {% if contact.type == 'B' %}
      <tr>
        <td><div onclick="pick_contact('B', '{{contact.contact}}', '{{contact.name}}')">{{ contact.contact }}</div></td>
        <td><div onclick="pick_contact('B', '{{contact.contact}}', '{{contact.name}}')">{{ contact.name }}</div></td>
        <td><div onclick="pick_contact('B', '{{contact.contact}}', '{{contact.name}}')">{{ contact.inn }}</div></td>
        <td><div onclick="pick_contact('B', '{{contact.contact}}', '{{contact.name}}')">{{ contact.email1 }}</div></td>
        <td><div onclick="pick_contact('B', '{{contact.contact}}', '{{contact.name}}')">{{ contact.idtelegram }}</div></td>
      </tr>
      {% endif %}
      {% endfor %}
</tbody></table></div></div>

<div>
  <h5 class="block_name_detail_page">{{ data.block_name }} [ ID {{ data.id }} ]</h5>
  {% if request.user.profile.type == 'O' %}
  <div {% if entity.posted %}class="div_posted_status"{% else %}class="div_not_posted_status"{% endif %} >
    Статус проводки: {% if not entity.posted %}НЕ {% endif %}ПРОВЕДЕН
  </div>
  {% endif %}
</div>

<form class='detail_form' action="" method="post">
  <div class="buttons_area">
    {% if request.user.profile.type == 'O' %}
      {% if not entity.posted %}
        <input type="submit" value="SAVE">
        {{ link.post }}<input type="button" value="POST"></a>
        {{ link.delete }}<input type="button" value="DELETE"></a>
      {% else %}
        {{ link.rollback }}<input type="button" value="ROLLBACK"></a>
      {% endif %}
    {% endif %}
      {{ link.close }}<input type="button" value="CLOSE"></a>
  </div>
  <div class="form_fields_area">
    {{ form.as_p }}
    {% csrf_token %}
  </div>
  {% if not entity.posted %}<div style="color:SlateGray"><span style="color:red;">*</span> - обязательные поля при проводке документа</div>{% endif %}
</form>

{% if data.entity != 'contact' %}
  <hr>
  <h5 class="block_name">Документы</h5>
  {% if not entity.posted %}
  <div class='buttons_area'>
    <a href="{% url 'svh_service:document_add' data.entity entity.id %}">
      <input type="button" value="ADD"></a>
    </a>
  </div>
  {% endif %}
  <table id="table" data-toggle="table" data-show-export="true" data-pagination="true" data-show-columns="true"
      data-search="true" data-advanced-search="true" data-id-table="advancedTable" data-reorderable-columns="true"
      data-resizable="true" data-search-align="left" data-buttons-align="left">  
    <thead><tr>
      <th data-sortable="true" data-field="docnum">Номер</th>
      <th data-sortable="true" data-field="docdate">Дата</th>
      <th data-sortable="true" data-field="docname">Наименование</th>
      <th data-sortable="true" data-field="nfile">Файл</th>
    </tr></thead>
    <tbody>
      {% for document in documents %}
      <tr>
        <td><a href="{% url 'svh_service:document_update' document.id %}">{{ document.docnum }}</a></td>
        <td>{{ document.docdate }}</td>
        <td>{{ document.docname }}</td>
        <td>{{ document.nfile }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
{% endif %}

<script>
  {% if app_type == 'operator' and not is_posted %}
    document.getElementById("id_contact_name").addEventListener("click", function () {open_modal_catalog('V');},);
    document.getElementById("id_broker_name").addEventListener("click", function () {open_modal_catalog('B');},);
  {% endif %}
  var modal_catalog_client = document.getElementById("modal_catalog_client");
  var modal_catalog_broker = document.getElementById("modal_catalog_broker");

  function open_modal_catalog(contact_type) {
    //
    if (contact_type == 'V') {
      modal_catalog_client.style.display = "block";
    }
    else if (contact_type == 'B') {
      modal_catalog_broker.style.display = "block";
    }
  }

  function close_modal_catalog(contact_type) {
    //
    if (contact_type == 'V') {
      modal_catalog_client.style.display = "none";
    }
    else if (contact_type == 'B') {
      modal_catalog_broker.style.display = "none";
    }
  }

  function pick_contact(contact_type, picked_contact_id, picked_contact_name) {
    //
    if (contact_type == 'V') {
      var id_1 = 'id_contact'; var id_2 = 'id_contact_name'
      modal_catalog_client.style.display = "none";
    }
    else if (contact_type == 'B') {
      var id_1 = 'id_contact_broker'; var id_2 = 'id_broker_name'
      modal_catalog_broker.style.display = "none";
    }
    document.getElementById(id_1).value = picked_contact_id
    document.getElementById(id_2).value = picked_contact_name
  }

</script>

{% endblock %}