vitrina/svh_service/api/urls.py
from django.urls import path
from . import views

app_name = 'svh_service'

urlpatterns = [
    path('get_app_alive/', views.get_app_alive, name='get_app_alive'),
    path('get_app_stat/', views.get_app_stat, name='get_app_stat'),
]

vitrina/svh_service/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views


app_name = 'svh_service'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('consignments', views.consignment_list, name='consignment_list'),
    path('consignments/<int:id>/', views.consignment_update, name='consignment_update'),
    path('consignments/<int:id>/update', views.consignment_update, name='consignment_update'),
    path('consignments/<int:id>/delete', views.consignment_delete, name='consignment_delete'),
    path('consignments/<int:id>/post', views.consignment_post, name='consignment_post'),
    path('consignments/<int:id>/rollback', views.consignment_rollback, name='consignment_rollback'),
    path('consignments/<int:id>/close', views.consignment_close, name='consignment_close'),

    path('<str:entity_type>/object_add', views.object_add, name='object_add'),   #########

    path('erase_filters/<str:entity>/', views.erase_filters, name='erase_filters'),

    path('carpass', views.carpass_list, name='carpass_list'),
    path('carpass/<int:id>/', views.carpass_update, name='carpass_update'),
    path('carpass/<int:id>/update', views.carpass_update, name='carpass_update'),
    path('carpass/<int:id>/delete', views.carpass_delete, name='carpass_delete'),
    path('carpass/<int:id>/post', views.carpass_post, name='carpass_post'),
    path('carpass/<int:id>/rollback', views.carpass_rollback, name='carpass_rollback'),
    path('carpass/<int:id>/close', views.carpass_close, name='carpass_close'),

    path('documents/<str:entity_type>/<int:entity_id>/add_document', views.document_add, name='document_add'),
    path('documents/<int:id>/update', views.document_update, name='document_update'),
    path('documents/<int:id>/delete', views.document_delete, name='document_delete'),
    path('documents/<int:id>/close', views.document_close, name='document_close'),
    path('documents/<int:id>/download', views.document_download, name='document_download'),

    path('contacts', views.contact_list, name='contact_list'),
    path('contacts/<int:id>/', views.contact_update, name='contact_update'),
    path('contacts/<int:id>/update', views.contact_update, name='contact_update'),
    path('contacts/<int:id>/delete', views.contact_delete, name='contact_delete'),
    path('contacts/<int:id>/post', views.contact_post, name='contact_post'),
    path('contacts/<int:id>/rollback', views.contact_rollback, name='contact_rollback'),
    path('contacts/<int:id>/close', views.contact_close, name='contact_close'),
]

vitrina/vitrina/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('svh_service/', include('svh_service.urls', namespace='svh_service')),
    path('api/', include('svh_service.api.urls', namespace='api')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vitrina/svh_service/api/views.py
from datetime import datetime
from django.contrib.auth.models import User
from rest_framework import permissions, viewsets
from svh_service.models import Consignment, Carpass, Contact, Document, Uemail
from svh_service.api.serializers import StatSerializer, IsAliveSerializer
from django.http import JsonResponse
from rest_framework.authentication import BasicAuthentication
from rest_framework.permissions import IsAuthenticated


# class UserViewSet(viewsets.ModelViewSet):
#     queryset = User.objects.all().order_by('-date_joined')
#     serializer_class = UserSerializer
#     permission_classes = [permissions.IsAuthenticated]


def get_app_alive(request):
    # api endpoint to get app is_alive status
    current_datetime = datetime.now()
    app_name = 'svh_service'
    is_alive = True

    data = {'current_datetime': current_datetime,
            'app_name': app_name, 
            'is_alive': is_alive,
            }
    
    serializer = IsAliveSerializer(data)
    data_serialized = serializer.data
    
    return JsonResponse(data_serialized, safe=False)


def get_app_stat(request):
    # api endpoint to get app statistics
    current_datetime = datetime.now()
    consignments = Consignment.objects.all()
    carpass = Carpass.objects.all()
    contacts = Contact.objects.all()
    documents = Document.objects.all()
    uemails = Uemail.objects.all()

    data = {'current_datetime': current_datetime,
            'consignments': len(consignments),
            'carpass': len(carpass),
            'contacts': len(contacts),
            'documents': len(documents),
            'uemails': len(uemails),
            }
    
    serializer = StatSerializer(data)
    data_serialized = serializer.data
    
    return JsonResponse(data_serialized, safe=False)

vitrina/svh_service/views.py
import sys, os, json, configparser
from django.shortcuts import render, get_object_or_404, redirect, HttpResponse
from .models import Consignment, Carpass, Contact, Document, Uemail
from .forms import ConsignmentForm, CarpassForm, ContactForm, DocumentForm
from .forms import ConsignmentPostedForm, CarpassPostedForm, ContactPostedForm, DocumentPostedForm
from .forms import ConsignmentFiltersForm, CarpassFiltersForm, ContactFiltersForm
from django.views.decorators.http import require_POST
from datetime import datetime, date
from django.conf import settings
from django.http import HttpResponse, Http404
from urllib.parse import quote
from django.contrib.auth.decorators import login_required
from django.utils.safestring import mark_safe

from django.contrib.auth import authenticate, login
from .forms import LoginForm
from pathlib import Path
from django.core.exceptions import ValidationError


config = configparser.ConfigParser()
config_file = os.path.join(Path(__file__).resolve().parent.parent, 'vitrina', 'config.ini')
if os.path.exists(config_file):
    config.read(config_file, encoding='utf-8')
else:
    print("error! config file doesn't exist"); sys.exit()

APP_TYPE = config['app']['app_type']
FILE_FILTERS = {}

TYPE_NAME = {
            "V": "участник ВЭД", 
            "B": "таможенный представитель (брокер)", 
            "O": "оператор СВХ", 
            "H": "руководство СВХ",
        }

# COMMON_VIEWS - CONSIGNMENT - CARPASS - DOCUMENT - CONTACT

#  COMMON_VIEWS *************************************
@login_required
def erase_filters(request, entity):
    # erase all filters data - by deleting json file with it
    if os.path.exists(FILE_FILTERS[entity]):
        os.remove(FILE_FILTERS[entity])
    return redirect(f'/svh_service/{entity}')


@login_required
def object_add(request, entity_type):
    # universal function for adding object (consignment, carpass, contact)

    entity, entity['consignment'], entity['carpass'] = {}, {}, {}
    entity['consignment'] = { 'model': Consignment, 'id_name': 'key_id' }
    entity['carpass'] = { 'model': Carpass, 'id_name': 'id_enter' }
    entity['contact'] = { 'model': Contact, 'id_name': 'contact' }

    # calculate new object id = get from db max related to entity_type (model) ID and increase it on 1
    object_id_list = entity[entity_type]['model'].objects.values_list(
        entity[entity_type]['id_name'], flat=True)
    if len(object_id_list) == 0:
        object_id_list = ['0']
    object_id_new = max(list(map(int, object_id_list))) + 1
    object_id_new = int(object_id_new) if entity_type == 'contact' else str(object_id_new)

    # create empty object with entity id only and save it to db
    c = entity[entity_type]['model']()
    c.__setattr__(entity[entity_type]['id_name'], object_id_new)
    c.save()

    # get id or the newest created object and redirect to update page
    get_object = entity[entity_type]['model'].objects.all().order_by('-id')[0]
    id_for_link = get_object.id
    entity_type_for_link = entity_type if entity_type == 'carpass' else entity_type+'s'
    return redirect(f'/svh_service/{entity_type_for_link}/{id_for_link}/update')


#  CONSIGNMENT ******************************************
@login_required
def consignment_list(request):
    """
    Список партии товаров
    """
    global FILE_FILTERS
    CONTACT_FOLDER = f'temp_files/{request.user.profile.contact}'
    FILE_FILTERS['consignments'] = CONTACT_FOLDER + '/consignments_filters.json'
    FILE_FILTERS['carpass'] = CONTACT_FOLDER + '/carpass_filters.json'
    FILE_FILTERS['contacts'] = CONTACT_FOLDER + '/contacts_filters.json'
    if not os.path.exists('temp_files'):
        os.mkdir('temp_files')
    if not os.path.exists(CONTACT_FOLDER):
        os.mkdir(CONTACT_FOLDER)

    if request.user.profile.type == 'O' and APP_TYPE == 'operator':
        consignments = Consignment.objects.all()
        documents = Document.objects.all()
    elif request.user.profile.type == 'O' and APP_TYPE == 'client':
        # if client try to login as operator svh
        return redirect('/svh_service/login')
    else:
        try:
            if request.user.profile.type == 'V':
                consignments = Consignment.objects.filter(posted=True).filter(contact=request.user.profile.contact)
            elif request.user.profile.type == 'B':
                consignments = Consignment.objects.filter(posted=True).filter(contact_broker=request.user.profile.contact)
        except:
            consignments = ''

        try:
            key_id_list = consignments.values_list("key_id", flat=True)
            documents = Document.objects.filter(guid_partia__in=key_id_list)
        except:
            documents = ''

    # фильтрация данных
    if request.method == 'POST':
        form_filters = ConsignmentFiltersForm(data=request.POST)
        if form_filters.is_valid():
            cd = form_filters.cleaned_data
            # save filters data into json file
            # cast datetime to str for ability of serializing
            cd_date_casted = form_filters.cleaned_data
            for d in cd_date_casted:
                if (type(cd_date_casted[d]) is date):
                    cd_date_casted[d] = cd_date_casted[d].strftime('%Y-%m-%d')
            cd_json = json.dumps(cd_date_casted)
            with open(FILE_FILTERS['consignments'], 'w', encoding='utf-8') as f:
                f.write(cd_json)

    else: # request.method == 'GET'
        # load filters data from json file if it exists
        if os.path.exists(FILE_FILTERS['consignments']):
            with open(FILE_FILTERS['consignments'], 'r') as f:
                cd = json.load(f)
            form_filters = ConsignmentFiltersForm(initial=cd)
        # create empty form if json file doesn't exit
        else:
            form_filters = ConsignmentFiltersForm()
            return render(request,
                    'shv_service/consignment/list.html',
                    {'consignments': consignments,
                    'documents': documents,
                    'form_filters': form_filters, })
    
    if cd['key_id']:
        consignments = consignments.filter(key_id=cd['key_id'])
    if cd['contact_name']:
        consignments = consignments.filter(contact_name=cd['contact_name'])
    if cd['broker_name']:
        consignments = consignments.filter(broker_name=cd['broker_name'])
    if cd['nttn']:
        consignments = consignments.filter(nttn=cd['nttn'])
    if cd['dkd']:
        consignments = consignments.filter(dkd=cd['dkd'])
    if cd['dater_from']:
        consignments = consignments.filter(dater__gte=cd['dater_from'])
    if cd['dater_to']:
        consignments = consignments.filter(dater__lte=cd['dater_to'])
    if cd['dateo_from']:
        consignments = consignments.filter(dateo__gte=cd['dateo_from'])
    if cd['dateo_to']:
        consignments = consignments.filter(dateo__lte=cd['dateo_to'])
    if cd['car']:
        consignments = consignments.filter(car=cd['car'])
    if cd['on_terminal']:
        consignments = consignments.filter(dateo__isnull=True)

    return render(request,
                  'shv_service/consignment/list.html',
                  {'consignments': consignments,
                   'documents': documents,
                   'form_filters': form_filters, })


@login_required
def consignment_update(request, id):
    consignment = get_object_or_404(Consignment, id=id)
    documents = Document.objects.filter(guid_partia=consignment.key_id)
    contacts = Contact.objects.filter(posted=True)

    if request.method == 'POST':
        form = ConsignmentForm(request.POST, instance=consignment)
        if form.is_valid():
            form.save()
    else:  # request.method == 'GET
        if consignment.posted:
            form = ConsignmentPostedForm(instance=consignment)
        else:
            form = ConsignmentForm(instance=consignment)

    # various data for render template
    data = {}
    data['block_name'] = 'Партия товаров'
    data['entity'] = 'consignment'
    data['id'] = consignment.key_id

    link = {}  #  links for buttons
    for k in ['post', 'delete', 'rollback', 'close']:
        link[k] = mark_safe(f'<a href="/svh_service/consignments/{id}/{k}">')

    context_data = {'form': form,
        'data': data, 
        'entity': consignment,
        'documents': documents,
        'contacts': contacts,
        'link': link,
        'app_type': APP_TYPE,
        'is_posted': consignment.posted}

    return render(request,
        'shv_service/update_universal.html',
        context=context_data)


@login_required
def consignment_delete(request, id):
    consignment = get_object_or_404(Consignment, id=id)
    
    if request.method == 'POST':
        consignment.delete()
        return redirect('/svh_service/consignments')
    
    return render(request,
                  'shv_service/consignment/delete.html',
                  {'consignment': consignment})


def check_fields_data(object, check_fields):
    # ПРОВЕРКИ ДАННЫХ
    entity_fields = object.__dict__
    empty_fields_list = []
    is_approved = True
    error_msg = []
    for e in list(check_fields.keys()):
        if entity_fields[e] in ['', None]:
            empty_fields_list.append(f'[ {check_fields[e]} ] не заполнено')
    if len(empty_fields_list) > 0:
        is_approved = False
        error_msg = empty_fields_list
    elif hasattr(object, 'contact_name'):
        contact = Contact.objects.filter(name=object.contact_name).filter(posted=True)
        if not contact:
            is_approved = False
            error_msg.append(f'Клиент {object.contact_name} отсутствует или не проведен в разделе Организации')
        # contact = get_object_or_404(Contact, contact=object.contact)

    return is_approved, error_msg



@login_required
def consignment_post(request, id):
    consignment = get_object_or_404(Consignment, id=id)

    # ПРОВЕРКИ ДАННЫХ
    is_approved, error_msg = check_fields_data(object=consignment, 

vitrina/svh_service/templates/shv_service/contact/_add.html
{% extends "shv_service/base.html" %}

{% block content %}

<h5 class="block_name">Добавление организации</h5>

<form class='detail_form' action="{% url 'svh_service:contact_add' %}" method="post">

  <div class="buttons_area">
    <input type="submit" value="SAVE">
    <a href="{% url 'svh_service:contact_list' %}"><input type='button' value="CANCEL"></a>
  </div>

  <div class="form_fields_area">
    {{ form.as_p }}
    {% csrf_token %}
  </div>

  <div>* - обязательные поля при проводке документа</div>
  
</form>

{% endblock %}

vitrina/svh_service/templates/shv_service/contact/_post.html
{% extends "shv_service/base.html" %}

{% block content %}

<h5 class="block_name">Подтверждение проводки</h5>
<form class='detail_form' action="" method="post">
  {% csrf_token %}
  <div class="buttons_area">
    {% if is_approved == True %}<input type="submit" value="POST">
    {% else %}<div>{{ error_msg }}</div><br>
    {% endif %}
    <a href="{% url 'svh_service:contact_update' contact.id %}"><input type="button" value="CANCEL"></a>
  </div>
</form>

{% endblock %}

vitrina/svh_service/templates/shv_service/contact/_update.html
{% extends "shv_service/base.html" %}

{% block content %}

<h5 class="block_name">Организация</h5>

<form class='detail_form' action="" method="post">

  <div class="buttons_area">
    {% if not contact.posted %}
      <input type="submit" value="SAVE">
      <a href="{% url 'svh_service:contact_post' contact.id %}"><input type="button" value="POST"></a>
      <a href="{% url 'svh_service:contact_delete' contact.id %}"><input type="button" value="DELETE"></a>
    {% else %}
      <a href="{% url 'svh_service:contact_rollback' contact.id %}"><input type="button" value="ROLLBACK"></a>
    {% endif %}
    <a href="{% url 'svh_service:contact_close' contact.id %}"><input type="button" value="CLOSE"></a>
  </div>

  <div class="form_fields_area">
    <div {% if contact.posted %}class="div_posted_status"{% else %}class="div_not_posted_status"{% endif %} >
      Статус проводки: {% if not contact.posted %}НЕ {% endif %}ПРОВЕДЕН
    </div>

    {{ form.as_p }}
    {% csrf_token %}
  </div>
  
</form>

{% endblock %}

vitrina/svh_service/templates/shv_service/contact/add.html
{% extends "shv_service/base.html" %}

{% block content %}

<h5 class="block_name">Добавление организации</h5>

<form class='detail_form' action="{% url 'svh_service:contact_add' %}" method="post">

  <div class="buttons_area">
    <input type="submit" value="SAVE">
    <a href="{% url 'svh_service:contact_list' %}"><input type='button' value="CANCEL"></a>
  </div>

  <div class="form_fields_area">
    {{ form.as_p }}
    {% csrf_token %}
  </div>

  <div>* - обязательные поля при проводке документа</div>
  
</form>

{% endblock %}

vitrina/svh_service/templates/shv_service/contact/close.html
{% extends "shv_service/base.html" %}

{% block content %}

<h5 class="block_name">Подтверждение выхода</h5>
<form class='detail_form' action="" method="post">
  {% csrf_token %}
  <div class="buttons_area">
    <input type="submit" value="YES">
    <a href="{% url 'svh_service:contact_update' contact.id %}"><input type="button" value="NO"></a>
  </div>
</form>

{% endblock %}

vitrina/svh_service/templates/shv_service/contact/delete.html
{% extends "shv_service/base.html" %}

{% block content %}

<h5 class="block_name">Подтверждение удаления</h5>
<form class='detail_form' action="" method="post">
  {% csrf_token %}
  <div class="buttons_area">
    <input type="submit" value="DELETE">
    <a href="{% url 'svh_service:contact_update' contact.id %}"><input type="button" value="CANCEL"></a>
  </div>
</form>

{% endblock %}

vitrina/svh_service/templates/shv_service/contact/list.html
{% extends "shv_service/base.html" %}

{% block content %}
  <h5 class="block_name">Организации</h5>

  <div class='buttons_area'>
    <a href="{% url 'svh_service:object_add' 'contact' %}"><input type="button" value="ADD"></a>
  </div>

  <form class='filters_form' action="" method="post">
    <div class="filters_form_btns">
      <input type="submit" value="APPLY">
      <a href="{% url 'svh_service:erase_filters' 'contacts' %}"><input type="button" value="CLEAR"></a>
    </div>
    <div class="filters_form_inputs">
      {{ form_filters.as_table }}
      {% csrf_token %}
    </div>
  </form>

  <table
    id="table"
    data-toggle="table"
    data-show-export="true"
    data-pagination="true"
    data-show-columns="true"
    data-search="true"
    data-advanced-search="true"
    data-id-table="advancedTable"
    data-reorderable-columns="true"
    data-resizable="true"
    data-search-align="left"
    data-buttons-align="left"
  >  
    <thead>
    <tr>
      <th data-sortable="true" data-field="contact">Код клиента</th>
      <th data-sortable="true" data-field="type">Тип</th>
      <th data-sortable="true" data-field="name">Наименование организации</th>
      <th data-sortable="true" data-field="inn">ИНН</th>
      <th data-sortable="true" data-field="email1">E-mail</th>
      <th data-sortable="true" data-field="idtelegram">Telegram ID</th>
    </tr>
    </thead>
    <tbody>
      {% for contact in contacts %}
      {% if not contact.posted %}<tr style="background-color: LavenderBlush;">
      {% else %}<tr>{% endif %}
        <td><a href="{% url 'svh_service:contact_update' contact.id %}">{{ contact.contact }}</a></td>
        <td>{{ contact.type_name }}</td>
        <td>{{ contact.name }}</td>
        <td>{{ contact.inn }}</td>
        <td>{{ contact.email1 }}</td>
        <td>{{ contact.idtelegram }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  
{% endblock %}

vitrina/svh_service/templates/shv_service/contact/post.html
{% extends "shv_service/base.html" %}

{% block content %}

<h5 class="block_name">Подтверждение проводки</h5>
<form class='detail_form' action="" method="post">
  {% csrf_token %}
  <div class="buttons_area">
    {% if is_approved == True %}<input type="submit" value="POST">
    {% else %}<div>{{ error_msg }}</div><br>
    {% endif %}
    <a href="{% url 'svh_service:contact_update' contact.id %}"><input type="button" value="CANCEL"></a>
  </div>
</form>

{% endblock %}

vitrina/svh_service/templates/shv_service/contact/rollback.html
{% extends "shv_service/base.html" %}

{% block content %}

<h5 class="block_name">Подтверждение отката</h5>
<form class='detail_form' action="" method="post">
  {% csrf_token %}
  <div class="buttons_area">
    <input type="submit" value="ROLLBACK">
    <a href="{% url 'svh_service:contact_update' contact.id %}"><input type="button" value="CANCEL"></a>
  </div>
</form>

{% endblock %}

vitrina/svh_service/templates/shv_service/contact/update.html
{% extends "shv_service/base.html" %}

{% block content %}

<h5 class="block_name">Организация</h5>

<form class='detail_form' action="" method="post">

  <div class="buttons_area">
    {% if not contact.posted %}
      <input type="submit" value="SAVE">
      <a href="{% url 'svh_service:contact_post' contact.id %}"><input type="button" value="POST"></a>
      <a href="{% url 'svh_service:contact_delete' contact.id %}"><input type="button" value="DELETE"></a>
    {% else %}
      <a href="{% url 'svh_service:contact_rollback' contact.id %}"><input type="button" value="ROLLBACK"></a>
    {% endif %}
    <a href="{% url 'svh_service:contact_close' contact.id %}"><input type="button" value="CLOSE"></a>
  </div>

  <div class="form_fields_area">
    <div {% if contact.posted %}class="div_posted_status"{% else %}class="div_not_posted_status"{% endif %} >
      Статус проводки: {% if not contact.posted %}НЕ {% endif %}ПРОВЕДЕН
    </div>

    {{ form.as_p }}
    {% csrf_token %}
  </div>
  
</form>

{% endblock %}